---
name: Robustness Nightly
permissions: read-all
on:
  # schedules always run against the main branch, hence we have to create separate jobs
  # with individual checkout actions for each of the active release branches
  schedule:
    - cron: '25 9 * * *' # runs every day at 09:25 UTC

  # workflow_dispatch enables manual testing of this job by maintainers
  workflow_dispatch:

jobs:
  main-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 150
      testTimeout: 200m
      artifactName: main-arm64
      runs-on: "['actuated-arm64-12cpu-8gb']"
      scenario: TestRobustnessExploratory
      lazyfsEnabled: false
  release-35-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.5
      count: 150
      testTimeout: 200m
      artifactName: release-35-arm64
      runs-on: "['actuated-arm64-12cpu-8gb']"
      scenario: TestRobustnessExploratory
      lazyfsEnabled: false
